version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 10s
      retries: 5
    env_file:
      - .env
  sync:
    build:
      context: .
      dockerfile: Dockerfile.sync
    depends_on:
      - api

volumes:
  database-data: